### ISSUE TITLE
Encoding troubles

### ISSUE THREAD

**Issue by Jonathan-Rosewood** [Southclaws/announce-backend#26] opened 2017-10-24 09:03 UTC
![2017-10-24 12 02 46](https://user-images.githubusercontent.com/2553512/31933957-4d79a746-b8b3-11e7-844d-dbc65e762693.png)

**Comment by Southclaws** [comment] 2017-10-24 10:12
Duplicate of #19

**Closed as completed by Southclaws** 2017-10-24 10:12 UTC
