### ISSUE TITLE
Duplicate server entries

### ISSUE THREAD

**Issue by BigETI** [Southclaws/announce-backend#24] opened 2017-10-02 13:48 UTC
![screenshot_20171002-154358](https://user-images.githubusercontent.com/4518424/31080449-05c5b22c-a789-11e7-9b06-c46f6327b0f3.png)
To avoid this, the host name has to be resolved to the IP address.

**Comment by Southclaws** [comment] 2018-10-05 08:52
Duplicate of #16

**Closed as completed by Southclaws** 2018-10-05 08:52 UTC
